spring:
  profiles:
    active: @spring.profiles.active@

  app:
    datasource:
      url: jdbc:postgresql://localhost:5432/demodb
      username: postgres
      password: password
      pool-size: 30

